name: EcoMode
version: 1.2.3
main: com.ghostchu.plugins.riabandwidthsaver.RIABandwidthSaver
api-version: '1.20'
depend:
  - packetevents
softdepend:
  - CMI
  - Essentials
commands:
  riabandwidthsaver:
    usage: /riabandwidthsaver